# function for cost (4th) element key, will be used for cost
def take_cost(elem):
    return elem[4]


# Open a file
fo = open("test.txt", "r+")
print ("Name of the file: ", fo.name)


# function for read all the output line by line and store it to line_list
line = fo.readlines()
line_list = []
for i in range(0, len(line), 5):
    line_list.append(line[i:i+5])


# function for make the total cost into integer and remove whitespace
for i in range(len(line_list)):
    line_list[i][len(line_list[i])-1] = line_list[i][len(line_list[i])-1].replace('\n', '')
    line_list[i][len(line_list[i])-1] = int(line_list[i][len(line_list[i])-1])


# This is the example of new output will be generated by CRO
line2 = ['### ----------- Test ------------  ###\n', 'Final Sequence:\n', '[[3, 6, 2, 1, 5, 4], [5, 3, 6, 4, 2, 1], [3, 5, 6, 1, 2, 4], [5, 6, 1, 3, '
                                          '2, 4], [2, 5, 1, 6, 3, 4]]\n', 'Final Cost:\n', 9]


# this is the check for total_lines whether it will append new output or not
total_lines = list(line_list)
flag_same_cost = False

for item in total_lines:
    if line2[4] == item[4]:
        flag_same_cost = True

if not flag_same_cost:
    total_lines.append(line2)


# Here we will sort all the outputs using the cost value
total_lines.sort(key=take_cost)
# print('total_lines: ', total_lines)


# this is the path where we store the updated result
# in main code this might be [molecule table]
path = "C:/Users/Rakibul Hasan/PycharmProjects/LearnPythonBasic/textfile/output/test"
problem_no = '7'
f = open(path+'.result'+problem_no+'.txt', 'w+')
for i in range (0,4):
    for item in total_lines[i]:
        f.write(str(item))
    f.write('\n')
f.close()
